Support web vitals in logjam-prometheus-exporter
skaes/logjam-tools pull request #43
Opened 2021-05-03 12:44 UTC by Shadi

related to https://github.com/skaes/logjam-tools/pull/41

Add support for web vitals in logjam-prometheus-exporter

2021-05-10 15:35 UTC, 0robustus1 commented on go/prometheusexporter/collector/collector.go
> +			Name:    "logjam:action:webvitals_lcp_seconds",
The other logjam metrics seem to include the `_distribution_` infix for histogram metrics. Should we add this here as well?

2021-05-14 09:34 UTC, Shadi commented on go/prometheusexporter/collector/collector.go
> +			vitals["fid"] = *vital.FID
I added webvitals to metric, this would avoid the need for building this map.

2021-05-17 08:26 UTC, 0robustus1 requested changes

2021-05-17 08:26 UTC, 0robustus1 commented on go/prometheusexporter/collector/collector.go
> +			c.actionMetrics.webvitalsFid.With(labels).Observe(*vital.FID)
FID is a value measured in milliseconds: https://github.com/skaes/logjam-tools/blob/add-web-vitals-endpoint/go/formats/webvitals/webvitals.go#L29-L30

We'll need to convert it to seconds.

2021-05-17 08:26 UTC, 0robustus1 commented on go/prometheusexporter/collector/collector.go
> +			c.actionMetrics.webvitalsLcp.With(labels).Observe(*vital.LCP)
LCP is a value measured in milliseconds: https://github.com/skaes/logjam-tools/blob/add-web-vitals-endpoint/go/formats/webvitals/webvitals.go#L26-L27

We'll need to convert it to seconds.

2021-05-17 13:35 UTC, 0robustus1 approved these changes

2021-05-17 13:37 UTC, merged